title: Van Vo Studio
description: Website under construction
show_downloads: true
google_analytics:
remote_theme: tuur29/pages-themes-cayman
darkmode: false
hide_first_title: false
syntax_theme:
colors:
    gradient_left: "#155799"
    gradient_right: "#155799"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
buttons:
      zip_url: http://example.com/
      zip_title: Title
      zip_hide: true
      tar_url: http://example.com/
      tar_title: Title
      tar_hide: true
      github_hide: true # hides "View on Github"
